---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/22 9:59
---
local BasePlugin = require "kong.plugins.base_plugin"
local iputils = require "resty.iputils"

local new_tab
do
  local ok
  ok, new_tab = pcall(require, "table.new")
  if not ok then
    new_tab = function() return {} end
  end
end


-- cache of parsed CIDR values
local cache = {}


local DynameUpstreamHandler = BasePlugin:extend()

DynameUpstreamHandler.PRIORITY = 480
DynameUpstreamHandler.VERSION = "0.0.1"

local function cidr_cache(cidr_tab)
  local cidr_tab_len = #cidr_tab

  local parsed_cidrs = new_tab(cidr_tab_len, 0) -- table of parsed cidrs to return

  -- build a table of parsed cidr blocks based on configured
  -- cidrs, either from cache or via iputils parse
  -- TODO dont build a new table every time, just cache the final result
  -- best way to do this will require a migration (see PR details)
  for i = 1, cidr_tab_len do
    local cidr        = cidr_tab[i]
    local parsed_cidr = cache[cidr]

    if parsed_cidr then
      parsed_cidrs[i] = parsed_cidr

    else
      -- if we dont have this cidr block cached,
      -- parse it and cache the results
      local lower, upper = iputils.parse_cidr(cidr)

      cache[cidr] = { lower, upper }
      parsed_cidrs[i] = cache[cidr]
    end
  end

  return parsed_cidrs
end


function DynameUpstreamHandler:new()
 DynameUpstreamHandler.super.new(self, "DynameUpstream")
end

function DynameUpstreamHandler:init_worker()
  DynameUpstreamHandler.super.init_worker(self)
  local ok, err = iputils.enable_lrucache()
  if not ok then
    ngx.log(ngx.ERR, "[DynameUpstream] Could not enable lrucache: ", err)
  end
end


function DynameUpstreamHandler:access(conf)
  DynameUpstreamHandler.super.access(self)
  local AllowIp = false
  local binary_remote_addr = ngx.var.binary_remote_addr

  -- your custom code here

  if conf.ip and #conf.ip > 0 then
    AllowIp = iputils.binip_in_cidrs(binary_remote_addr, cidr_cache(conf.ip))
  end

  if AllowIp and binary_remote_addr then
    local ok, err = kong.service.set_upstream(conf.upstream)
    if not ok then
        kong.log.err(err)
        return
    end
  end

end

return DynameUpstreamHandler